import { MigrationInterface, QueryRunner } from 'typeorm'

export class BillingSchemaEnhancement1740447708857 implements MigrationInterface {
    name = 'BillingSchemaEnhancement1740447708857'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d229"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_e76bae1780b77e56aab1h2asd4"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_e213b811b01405a42309a6a410"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d230"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_paid_plan_organizationId"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_trial_plan_userId"`)
        await queryRunner.query(
            `CREATE TABLE "subscription" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entityType" character varying(50) NOT NULL, "entityId" uuid NOT NULL, "organizationId" uuid, "subscriptionType" character varying(50) NOT NULL, "stripeSubscriptionId" character varying NOT NULL, "stripeSubscriptionItemId" character varying NOT NULL, "status" character varying NOT NULL, "creditsLimit" integer NOT NULL, "currentPeriodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "currentPeriodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_77dbeeb547dcfa35907431005b4" UNIQUE ("stripeSubscriptionId"), CONSTRAINT "UQ_878a57bea0296b7a90a67f10f5e" UNIQUE ("stripeSubscriptionItemId"), CONSTRAINT "UQ_c56e60bc943bbf16bff5967b6f7" UNIQUE ("entityType", "entityId"), CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id"))`
        )
        await queryRunner.query(`CREATE INDEX "IDX_adccc182c138222d2fc5404cfe" ON "subscription" ("entityType") `)
        await queryRunner.query(`CREATE INDEX "IDX_404bc7ad0e4734744372d656fe" ON "subscription" ("entityId") `)
        await queryRunner.query(`CREATE INDEX "IDX_8ccdfc22892c16950b568145d5" ON "subscription" ("organizationId") `)
        await queryRunner.query(
            `CREATE TABLE "usage_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entityType" character varying(50) NOT NULL, "entityId" uuid NOT NULL, "organizationId" uuid, "resourceType" character varying(50) NOT NULL, "quantity" integer NOT NULL, "creditsConsumed" integer NOT NULL, "stripeMeterEventId" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_797d3f1dfd307095af5e4fd8457" PRIMARY KEY ("id"))`
        )
        await queryRunner.query(`CREATE INDEX "IDX_2077b438c7d5d48881c421dcc8" ON "usage_event" ("entityType") `)
        await queryRunner.query(`CREATE INDEX "IDX_dfa5f891e7bc640519201dc148" ON "usage_event" ("entityId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f55608e2ecbb73851d47bdca71" ON "usage_event" ("organizationId") `)
        await queryRunner.query(`CREATE INDEX "IDX_60859f43a55aa0a2cfec014a9c" ON "usage_event" ("entityType", "entityId", "createdDate") `)
        await queryRunner.query(`CREATE INDEX "IDX_adc16872e0c96cca911ba0cbd3" ON "usage_event" ("organizationId", "createdDate") `)
        await queryRunner.query(
            `CREATE TABLE "blocking_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entityType" character varying(50) NOT NULL, "entityId" uuid NOT NULL, "organizationId" uuid, "isBlocked" boolean NOT NULL DEFAULT false, "reason" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c18f866034d2072d52c8020e7ac" UNIQUE ("entityType", "entityId"), CONSTRAINT "PK_b360b38c547d299bd3207935b7c" PRIMARY KEY ("id"))`
        )
        await queryRunner.query(`CREATE INDEX "IDX_82e5717557bcee0ae66291863d" ON "blocking_status" ("entityType") `)
        await queryRunner.query(`CREATE INDEX "IDX_46b358af2c6024a5b7b293de89" ON "blocking_status" ("entityId") `)
        await queryRunner.query(`CREATE INDEX "IDX_75a323d637f69648fd405ad770" ON "blocking_status" ("organizationId") `)
        await queryRunner.query(
            `CREATE TABLE "stripe_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stripeEventId" character varying NOT NULL, "eventType" character varying NOT NULL, "eventData" jsonb NOT NULL, "processed" boolean NOT NULL DEFAULT false, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e346c225221ea580307a359231c" UNIQUE ("stripeEventId"), CONSTRAINT "PK_7a91ab435defe9ce0ee6fb6f7f7" PRIMARY KEY ("id"))`
        )
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "lastUsedAt"`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "isActive"`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "metadata"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_442b9a2cff872736117c8742b1"`)
        await queryRunner.query(`ALTER TABLE "chat_flow" DROP COLUMN "parentChatflowId"`)
        await queryRunner.query(`ALTER TABLE "chat_flow" ADD "parentChatflowId" text`)
        await queryRunner.query(`ALTER TABLE "chat_message" ALTER COLUMN "chatType" DROP DEFAULT`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "name" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "description" text`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "status"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "status" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store_file_chunk" ALTER COLUMN "pageContent" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "chat_message_feedback" ALTER COLUMN "rating" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "name" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "email"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "email" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "phone"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "phone" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "result"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "result" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "flowData"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "flowData" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP CONSTRAINT "PK_96109043dd704f53-9830ab78f0"`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "id"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "id" character varying(20) NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD CONSTRAINT "PK_0a1358bea3e5a3ba047b6e4959c" PRIMARY KEY ("id")`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiKey"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiKey" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiSecret"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiSecret" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "keyName"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "keyName" text NOT NULL`)
        await queryRunner.query(`DROP INDEX "public"."IDX_dfda472c0af7812401e592b6a6"`)
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "organizationId"`)
        await queryRunner.query(`ALTER TABLE "user" ADD "organizationId" uuid array`)
        await queryRunner.query(`ALTER TABLE "paid_plan" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`)
        await queryRunner.query(`ALTER TABLE "trial_plan" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`)
        await queryRunner.query(`CREATE INDEX "IDX_442b9a2cff872736117c8742b1" ON "chat_flow" ("parentChatflowId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d229" ON "chat_message_feedback" ("chatflowid") `)
        await queryRunner.query(`CREATE INDEX "IDX_4572bbe0437c04b9842d802a0c" ON "upsert_history" ("chatflowid") `)
        await queryRunner.query(`CREATE INDEX "IDX_dfda472c0af7812401e592b6a6" ON "user" ("organizationId") `)
        await queryRunner.query(`CREATE INDEX "IDX_7bf44502ed80d501adc5086b50" ON "paid_plan" ("organizationId") `)
        await queryRunner.query(`CREATE INDEX "IDX_a2200e5d14c95730c1cfb3f9d2" ON "trial_plan" ("userId") `)
        await queryRunner.query(
            `ALTER TABLE "chat" ADD CONSTRAINT "FK_64635a7018308a5399c37eb1932" FOREIGN KEY ("chatflowId") REFERENCES "chat_flow"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`
        )
        await queryRunner.query(
            `ALTER TABLE "chat" ADD CONSTRAINT "FK_ae88d8de23e69a0d57105a5bce5" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`
        )
        await queryRunner.query(
            `ALTER TABLE "chat" ADD CONSTRAINT "FK_2630d5ea3b9b8a5457ce97abb14" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`
        )
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_2630d5ea3b9b8a5457ce97abb14"`)
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_ae88d8de23e69a0d57105a5bce5"`)
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_64635a7018308a5399c37eb1932"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_a2200e5d14c95730c1cfb3f9d2"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_7bf44502ed80d501adc5086b50"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_dfda472c0af7812401e592b6a6"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_4572bbe0437c04b9842d802a0c"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d229"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_442b9a2cff872736117c8742b1"`)
        await queryRunner.query(`ALTER TABLE "trial_plan" ALTER COLUMN "id" DROP DEFAULT`)
        await queryRunner.query(`ALTER TABLE "paid_plan" ALTER COLUMN "id" DROP DEFAULT`)
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "organizationId"`)
        await queryRunner.query(`ALTER TABLE "user" ADD "organizationId" uuid`)
        await queryRunner.query(`CREATE INDEX "IDX_dfda472c0af7812401e592b6a6" ON "user" ("organizationId") `)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "keyName"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "keyName" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiSecret"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiSecret" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiKey"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiKey" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP CONSTRAINT "PK_0a1358bea3e5a3ba047b6e4959c"`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "id"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD CONSTRAINT "PK_96109043dd704f53-9830ab78f0" PRIMARY KEY ("id")`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "flowData"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "flowData" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "result"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "result" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "phone"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "phone" text`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "email"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "email" text`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "name" text`)
        await queryRunner.query(`ALTER TABLE "chat_message_feedback" ALTER COLUMN "rating" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store_file_chunk" ALTER COLUMN "pageContent" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "status"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "status" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "description" character varying`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "name" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "chat_message" ALTER COLUMN "chatType" SET DEFAULT 'INTERNAL'`)
        await queryRunner.query(`ALTER TABLE "chat_flow" DROP COLUMN "parentChatflowId"`)
        await queryRunner.query(`ALTER TABLE "chat_flow" ADD "parentChatflowId" uuid`)
        await queryRunner.query(`CREATE INDEX "IDX_442b9a2cff872736117c8742b1" ON "chat_flow" ("parentChatflowId") `)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "metadata" jsonb`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "isActive" boolean NOT NULL DEFAULT true`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "lastUsedAt" TIMESTAMP`)
        await queryRunner.query(`DROP TABLE "stripe_event"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_75a323d637f69648fd405ad770"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_46b358af2c6024a5b7b293de89"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_82e5717557bcee0ae66291863d"`)
        await queryRunner.query(`DROP TABLE "blocking_status"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_adc16872e0c96cca911ba0cbd3"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_60859f43a55aa0a2cfec014a9c"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f55608e2ecbb73851d47bdca71"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_dfa5f891e7bc640519201dc148"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_2077b438c7d5d48881c421dcc8"`)
        await queryRunner.query(`DROP TABLE "usage_event"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_8ccdfc22892c16950b568145d5"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_404bc7ad0e4734744372d656fe"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_adccc182c138222d2fc5404cfe"`)
        await queryRunner.query(`DROP TABLE "subscription"`)
        await queryRunner.query(`CREATE INDEX "IDX_trial_plan_userId" ON "trial_plan" ("userId") `)
        await queryRunner.query(`CREATE INDEX "IDX_paid_plan_organizationId" ON "paid_plan" ("organizationId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d230" ON "chat_message_feedback" ("chatflowid") `)
        await queryRunner.query(`CREATE INDEX "IDX_e213b811b01405a42309a6a410" ON "document_store_file_chunk" ("storeId") `)
        await queryRunner.query(`CREATE INDEX "IDX_e76bae1780b77e56aab1h2asd4" ON "document_store_file_chunk" ("docId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d229" ON "chat_message" ("chatflowid") `)
    }
}
