import { themes as prismThemes } from 'prism-react-renderer'
import type { Config } from '@docusaurus/types'
import type * as Preset from '@docusaurus/preset-classic'
import type * as OpenApiPlugin from 'docusaurus-plugin-openapi-docs'

const config: Config = {
    title: 'AnswerAgentAI',
    tagline: 'Intelligent Answers, Instantly',
    favicon: 'img/favicon.png',

    // Set the production url of your site here
    url: 'https://answeragent.ai',
    // Set the /<baseUrl>/ pathname under which your site is served
    // For GitHub pages deployment, it is often '/<projectName>/'
    baseUrl: '/',

    // GitHub pages deployment config.
    // If you aren't using GitHub pages, you don't need these.
    organizationName: 'AnswerAgentAI', // Usually your GitHub org/user name.
    projectName: 'answerai', // Usually your repo name.

    onBrokenLinks: 'log',
    onBrokenMarkdownLinks: 'warn',

    // Even if you don't use internationalization, you can use this field to set
    // useful metadata like html lang. For example, if your site is Chinese, you
    // may want to replace "en" with "zh-Hans".
    i18n: {
        defaultLocale: 'en',
        locales: ['en']
    },

    presets: [
        [
            'classic',
            {
                docs: {
                    sidebarPath: require.resolve('./sidebars.ts'),
                    // Set this to true to use autogenerated sidebars
                    routeBasePath: 'docs',
                    sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
                        const sidebarItems = await defaultSidebarItemsGenerator(args)
                        return sidebarItems
                    },
                    docItemComponent: '@theme/ApiItem'
                },
                blog: {
                    showReadingTime: true,
                    feedOptions: {
                        type: ['rss', 'atom'],
                        xslt: true
                    },
                    // Please change this to your repo.
                    onInlineTags: 'warn',
                    onInlineAuthors: 'warn',
                    onUntruncatedBlogPosts: 'warn'
                },
                theme: {
                    customCss: './src/css/custom.css'
                }
            } satisfies Preset.Options
        ]
    ],
    plugins: [
        [
            '@docusaurus/plugin-google-gtag',
            {
                trackingID: 'G-VD1X9LNG3N',
                anonymizeIP: true,
                id: 'gtag-analytics'
            }
        ],
        [
            '@docusaurus/plugin-google-gtag',
            {
                trackingID: 'AW-16804071963',
                anonymizeIP: true,
                id: 'gtag-ads'
            }
        ],
        [
            'docusaurus-plugin-openapi-docs',
            {
                id: 'api', // plugin id
                docsPluginId: 'classic', // configured for preset-classic
                config: {
                    assistants: {
                        specPath: 'openapi/assistants.yaml',
                        outputDir: 'docs/api/assistants',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    attachments: {
                        specPath: 'openapi/attachments.yaml',
                        outputDir: 'docs/api/attachments',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    chatMessage: {
                        specPath: 'openapi/chat-message.yaml',
                        outputDir: 'docs/api/chat-message',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    chatflows: {
                        specPath: 'openapi/chatflows.yaml',
                        outputDir: 'docs/api/chatflows',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    documentStore: {
                        specPath: 'openapi/document-store.yaml',
                        outputDir: 'docs/api/document-store',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    feedback: {
                        specPath: 'openapi/feedback.yaml',
                        outputDir: 'docs/api/feedback',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    leads: {
                        specPath: 'openapi/leads.yaml',
                        outputDir: 'docs/api/leads',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    prediction: {
                        specPath: 'openapi/prediction.yaml',
                        outputDir: 'docs/api/prediction',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    tools: {
                        specPath: 'openapi/tools.yaml',
                        outputDir: 'docs/api/tools',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    ping: {
                        specPath: 'openapi/ping.yaml',
                        outputDir: 'docs/api/ping',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    upsertHistory: {
                        specPath: 'openapi/upsert-history.yaml',
                        outputDir: 'docs/api/upsert-history',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    variables: {
                        specPath: 'openapi/variables.yaml',
                        outputDir: 'docs/api/variables',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    vectorUpsert: {
                        specPath: 'openapi/vector-upsert.yaml',
                        outputDir: 'docs/api/vector-upsert',
                        sidebarOptions: {
                            groupPathsBy: 'tag'
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                // Extract API name from the ID
                                const apiName = pageData.id.split('/').pop()?.replace('-api', '') || ''
                                const title = apiName.charAt(0).toUpperCase() + apiName.slice(1)

                                // Generate a simple introduction
                                let markdown = `# ${title} API\n\n`
                                markdown += `This section contains the API endpoints for the ${apiName} service.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The ${title} API provides endpoints for managing ${apiName} resources.\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key or OAuth token.\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options,
                    dataEngine: {
                        specPath: 'openapi/data-engine.yaml',
                        outputDir: 'docs/api/data-engine',
                        sidebarOptions: {
                            groupPathsBy: 'tag',
                            sidebarCollapsible: true,
                            sidebarCollapsed: false
                        },
                        markdownGenerators: {
                            createInfoPageMD: (pageData) => {
                                let markdown = `# Data Engine API\n\n`
                                markdown += `This section contains the API endpoints for managing structured data resources including domains, URLs, calls, tags, documents, tickets, and chats.\n\n`

                                markdown += `## Overview\n\n`
                                markdown += `The Data Engine API provides comprehensive CRUD operations for managing data across multiple domains with support for filtering, pagination, and advanced search capabilities.\n\n`

                                markdown += `## Resources\n\n`
                                markdown += `The API supports the following resource types:\n\n`
                                markdown += `- **Domains**: Website domain metadata and analysis\n`
                                markdown += `- **URLs**: Page-level analysis and content tracking\n`
                                markdown += `- **Calls**: Call logs with transcripts and sentiment analysis\n`
                                markdown += `- **Tags**: Shared taxonomy and categorization system\n`
                                markdown += `- **Documents**: Vector-embedded documents for semantic search\n`
                                markdown += `- **Tickets**: Support ticket management\n`
                                markdown += `- **Chats**: Chat conversation logs and analytics\n\n`

                                markdown += `## Authentication\n\n`
                                markdown += `All API requests require authentication using an API key. Include your API key in the Authorization header:\n\n`
                                markdown += `\`\`\`\n`
                                markdown += `Authorization: Bearer YOUR_API_KEY\n`
                                markdown += `\`\`\`\n\n`

                                markdown += `## Base URL\n\n`
                                markdown += `- **Production**: \`https://prod.studio.theanswer.ai/api/v1/data-engine\`\n`
                                markdown += `- **Local Development**: \`http://localhost:4000/api/v1/data-engine\`\n\n`

                                markdown += `## Features\n\n`
                                markdown += `- Full CRUD operations for all resources\n`
                                markdown += `- Advanced filtering and search capabilities\n`
                                markdown += `- Pagination support for large datasets\n`
                                markdown += `- Vector similarity search for documents\n`
                                markdown += `- Hierarchical tag system\n`
                                markdown += `- Metadata tracking for source system integration\n\n`

                                markdown += `## Rate Limiting\n\n`
                                markdown += `API calls are subject to rate limiting to ensure fair usage and system stability.\n\n`

                                markdown += `## Endpoints\n\n`
                                markdown += `Explore the available endpoints in the sidebar to learn more about specific operations.\n\n`

                                return markdown
                            },
                            createTagPageMD: () => ''
                        }
                    } satisfies OpenApiPlugin.Options
                }
            }
        ]
    ],
    themes: ['docusaurus-theme-openapi-docs'], // export theme components

    scripts: [],

    clientModules: [require.resolve('./src/chatbot-init.js')],

    headTags: [],

    themeConfig: {
        // Replace with your project's social card
        image: 'img/answer-angent-ai-ogimage.png',
        colorMode: {
            defaultMode: 'dark',
            disableSwitch: true,
            respectPrefersColorScheme: false
        },
        navbar: {
            logo: {
                alt: 'AnswerAgentAI Logo',
                src: 'img/answerai-wide-black.png',
                srcDark: 'img/answerai-logo-600-wide-white.png' // Add this line for dark mode logo
            },
            items: [
                {
                    to: '/how-it-works',
                    label: 'How It Works',
                    position: 'left'
                },
                {
                    to: '/data-engine',
                    label: 'Data Engine',
                    position: 'left'
                },
                {
                    to: '/agent-studio',
                    label: 'Agent Studio',
                    position: 'left'
                },
                {
                    to: '/intelligence-hub',
                    label: 'Intelligence Hub',
                    position: 'left'
                },
                {
                    type: 'dropdown',
                    label: 'Resources',
                    position: 'left',
                    items: [
                        {
                            to: '/docs/intro',
                            label: 'Documentation'
                        },
                        {
                            to: '/docs/api',
                            label: 'API Documentation'
                        },
                        {
                            to: '/learn',
                            label: 'Learn'
                        },
                        {
                            to: '/ai-workshops',
                            label: 'AI Workshops'
                        },
                        {
                            to: '/docs/use-cases',
                            label: 'Use Cases'
                        },
                        {
                            to: '/docs/community',
                            label: 'Support'
                        }
                    ]
                },
                {
                    to: '/blog',
                    label: 'Blog',
                    position: 'left'
                },
                {
                    type: 'html',
                    position: 'right',
                    value: '<div id="navbar-ask-alpha"></div>'
                },
                {
                    href: 'https://studio.theanswer.ai',
                    label: 'Sign In',
                    position: 'right'
                }
            ]
        },
        footer: {
            links: [
                {
                    title: 'Product',
                    items: [
                        {
                            to: '/how-it-works',
                            label: 'How It Works'
                        },
                        {
                            to: '/pricing',
                            label: 'Pricing'
                        },
                        {
                            to: '/docs/use-cases',
                            label: 'Use Cases'
                        },
                        {
                            to: '/jlinc-partnership',
                            label: 'J-Link Partnership'
                        }
                    ]
                },
                {
                    title: 'Developers',
                    items: [
                        {
                            to: '/docs/developers',
                            label: 'Documentation'
                        },
                        {
                            to: '/docs/api',
                            label: 'API Reference'
                        },
                        {
                            to: '/developers',
                            label: 'Quick Start'
                        },
                        {
                            label: 'GitHub',
                            href: 'https://github.com/the-answerai'
                        },
                        {
                            label: 'Discord',
                            href: 'https://discord.gg/X54ywt8pzj'
                        }
                    ]
                },
                {
                    title: 'Resources',
                    items: [
                        {
                            to: '/blog',
                            label: 'Blog'
                        },
                        {
                            to: '/ai-workshops',
                            label: 'AI Workshops'
                        },
                        {
                            to: '/docs/community',
                            label: 'Help Center'
                        },
                        {
                            label: 'Contact Support',
                            href: 'https://calendly.com/lastrev/answeragent-demo'
                        }
                    ]
                },
                {
                    title: 'Company',
                    items: [
                        {
                            label: 'About Us',
                            href: '/#about'
                        },
                        {
                            label: 'Privacy Policy',
                            href: '/privacy-policy'
                        },
                        {
                            label: 'Terms of Service',
                            href: '/terms-of-service'
                        },
                        {
                            label: 'Security',
                            href: '/how-it-works#security'
                        }
                    ]
                }
            ],
            copyright: `Copyright © ${new Date().getFullYear()} AnswerAI`
        },
        prism: {
            theme: prismThemes.github,
            darkTheme: prismThemes.dracula
        }
    } satisfies Preset.ThemeConfig
}

export default config
