name: Node CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '*'
permissions:
    contents: read
jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest]
                node-version: [20.17.0]
        runs-on: ${{ matrix.platform }}
        env:
            PUPPETEER_SKIP_DOWNLOAD: true
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: pnpm/action-setup@v4
              with:
                  version: 9.15.9
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
                  cache-dependency-path: 'pnpm-lock.yaml'
            - run: pnpm install
            # Auto-fix linting issues first
            - name: Auto-fix linting issues
              run: pnpm lint --fix
            # Check if there are any remaining unfixable issues
            - name: Check remaining linting issues
              run: pnpm lint
            - run: pnpm build
            - name: Cypress install
              run: pnpm cypress install
            - name: Install dependencies (Cypress Action)
              uses: cypress-io/github-action@v6
              with:
                  working-directory: ./
                  runTests: false
            - name: Cypress test
              uses: cypress-io/github-action@v6
              with:
                  install: false
                  working-directory: packages/server
                  start: pnpm start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 120
                  browser: chrome
