name: SonarCloud analysis

on:
    push:
        branches: ['production', 'enterprise', 'staging']
    pull_request:
        branches: ['production', 'enterprise', 'staging']
    workflow_dispatch:

permissions:
    pull-requests: read
    contents: read

jobs:
    Analysis:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Analyze with SonarCloud
              uses: SonarSource/sonarcloud-github-action@v2.2.0
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.projectKey=the-answerai_theanswer
                      -Dsonar.organization=the-answerai
